name: Snyk Security Scan

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  pull_request:
    branches:
      - main  # Adjust branch name if needed

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@master

      # Step 2: Set up Snyk CLI (use stable version instead of @master)
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master  # or specify the latest stable version

      # Step 3: Set up Go (adjust Go version as needed)
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      # Step 4: Run the Snyk test to scan for vulnerabilities
      - name: Snyk test
        run: snyk test

     # Monitor the project with Snyk (optional but recommended)
      - name: Monitor the project with Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}   
